// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "encryption_bp.h"

void BpFieldDescriptorsInitEncriptedHeader(struct EncriptedHeader *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->peer_id), BpUint(16, sizeof(uint16_t)), "peer_id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->ticks), BpUint(24, sizeof(uint32_t)), "ticks");
}

void BpXXXProcessEncriptedHeader(void *data, struct BpProcessorContext *ctx) {
    struct EncriptedHeader *m = (struct EncriptedHeader *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitEncriptedHeader(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 40, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatEncriptedHeader(void *data, struct BpJsonFormatContext *ctx) {
    struct EncriptedHeader *m = (struct EncriptedHeader *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitEncriptedHeader(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 40, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeEncriptedHeader(struct EncriptedHeader *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessEncriptedHeader((void *)m, &ctx);
    return 0;
}

int DecodeEncriptedHeader(struct EncriptedHeader *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessEncriptedHeader((void *)m, &ctx);
    return 0;
}

int JsonEncriptedHeader(struct EncriptedHeader *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatEncriptedHeader((void *)m, &ctx);
    return ctx.n;
}