// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__ENCRYPTION_PACKET_H__
#define __BITPROTO__ENCRYPTION_PACKET_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Number of bytes to encode struct EncriptedHeader
#define BYTES_LENGTH_ENCRIPTED_HEADER 5

struct EncriptedHeader {
    uint16_t peer_id; // 16bit
    uint32_t ticks; // 24bit
};

// Encode struct EncriptedHeader to given buffer s.
int EncodeEncriptedHeader(struct EncriptedHeader *m, unsigned char *s);
// Decode struct EncriptedHeader from given buffer s.
int DecodeEncriptedHeader(struct EncriptedHeader *m, unsigned char *s);
// Format struct EncriptedHeader to a json format string.
int JsonEncriptedHeader(struct EncriptedHeader *m, char *s);

void BpXXXProcessEncriptedHeader(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatEncriptedHeader(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif