// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "fcap_bp.h"

void BpFieldDescriptorsInitPacketHeader(struct PacketHeader *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->version), BpEnum(3, sizeof(Version)), "version");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->is_res), BpBool(), "is_res");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->reserved), BpUint(4, sizeof(uint8_t)), "reserved");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->id), BpUint(12, sizeof(uint16_t)), "id");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->len), BpUint(12, sizeof(uint16_t)), "len");
}

void BpXXXProcessPacketHeader(void *data, struct BpProcessorContext *ctx) {
    struct PacketHeader *m = (struct PacketHeader *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitPacketHeader(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 32, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPacketHeader(void *data, struct BpJsonFormatContext *ctx) {
    struct PacketHeader *m = (struct PacketHeader *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitPacketHeader(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 32, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePacketHeader(struct PacketHeader *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPacketHeader((void *)m, &ctx);
    return 0;
}

int DecodePacketHeader(struct PacketHeader *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPacketHeader((void *)m, &ctx);
    return 0;
}

int JsonPacketHeader(struct PacketHeader *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPacketHeader((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitPacketRequest(struct PacketRequest *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->header), BpMessage(32, sizeof(struct PacketHeader), BpXXXProcessPacketHeader, BpXXXJsonFormatPacketHeader), "header");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->cmd), BpUint(8, sizeof(uint8_t)), "cmd");
}

void BpXXXProcessPacketRequest(void *data, struct BpProcessorContext *ctx) {
    struct PacketRequest *m = (struct PacketRequest *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitPacketRequest(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 40, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPacketRequest(void *data, struct BpJsonFormatContext *ctx) {
    struct PacketRequest *m = (struct PacketRequest *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitPacketRequest(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 40, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePacketRequest(struct PacketRequest *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPacketRequest((void *)m, &ctx);
    return 0;
}

int DecodePacketRequest(struct PacketRequest *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPacketRequest((void *)m, &ctx);
    return 0;
}

int JsonPacketRequest(struct PacketRequest *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPacketRequest((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitPacketResponse(struct PacketResponse *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->header), BpMessage(32, sizeof(struct PacketHeader), BpXXXProcessPacketHeader, BpXXXJsonFormatPacketHeader), "header");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->status), BpEnum(8, sizeof(Status)), "status");
}

void BpXXXProcessPacketResponse(void *data, struct BpProcessorContext *ctx) {
    struct PacketResponse *m = (struct PacketResponse *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitPacketResponse(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 40, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPacketResponse(void *data, struct BpJsonFormatContext *ctx) {
    struct PacketResponse *m = (struct PacketResponse *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitPacketResponse(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 40, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePacketResponse(struct PacketResponse *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPacketResponse((void *)m, &ctx);
    return 0;
}

int DecodePacketResponse(struct PacketResponse *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPacketResponse((void *)m, &ctx);
    return 0;
}

int JsonPacketResponse(struct PacketResponse *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPacketResponse((void *)m, &ctx);
    return ctx.n;
}