// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__FCAP_PACKET_H__
#define __BITPROTO__FCAP_PACKET_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

#define MTU 255

#define HEADER_LEN 5

#define BODY_LEN 250

#define MAX_MESSAGE_ID 4095

#define MAX_BODY_LEN 4095

#define MAX_MTU_LEN 4100

typedef uint8_t Version; // 3bit

#define VERSION_V1 0
#define VERSION_V2 1
#define VERSION_V3 2
#define VERSION_V4 3
#define VERSION_V5 4
#define VERSION_V6 5
#define VERSION_V7 6
#define VERSION_V8 7

typedef uint8_t Status; // 8bit

#define STATUS_OK 0
#define STATUS_ERROR 1

// Number of bytes to encode struct PacketHeader
#define BYTES_LENGTH_PACKET_HEADER 4

struct PacketHeader {
    // 1 byte
    Version version; // 3bit
    bool is_res; // 1bit
    uint8_t reserved; // 4bit
    // 3 bytes
    uint16_t id; // 12bit
    uint16_t len; // 12bit
};

// Number of bytes to encode struct PacketRequest
#define BYTES_LENGTH_PACKET_REQUEST 5

struct PacketRequest {
    struct PacketHeader header; // 32bit
    uint8_t cmd; // 8bit
};

// Number of bytes to encode struct PacketResponse
#define BYTES_LENGTH_PACKET_RESPONSE 5

struct PacketResponse {
    struct PacketHeader header; // 32bit
    Status status; // 8bit
};

// Encode struct PacketHeader to given buffer s.
int EncodePacketHeader(struct PacketHeader *m, unsigned char *s);
// Decode struct PacketHeader from given buffer s.
int DecodePacketHeader(struct PacketHeader *m, unsigned char *s);
// Format struct PacketHeader to a json format string.
int JsonPacketHeader(struct PacketHeader *m, char *s);

// Encode struct PacketRequest to given buffer s.
int EncodePacketRequest(struct PacketRequest *m, unsigned char *s);
// Decode struct PacketRequest from given buffer s.
int DecodePacketRequest(struct PacketRequest *m, unsigned char *s);
// Format struct PacketRequest to a json format string.
int JsonPacketRequest(struct PacketRequest *m, char *s);

// Encode struct PacketResponse to given buffer s.
int EncodePacketResponse(struct PacketResponse *m, unsigned char *s);
// Decode struct PacketResponse from given buffer s.
int DecodePacketResponse(struct PacketResponse *m, unsigned char *s);
// Format struct PacketResponse to a json format string.
int JsonPacketResponse(struct PacketResponse *m, char *s);

void BpXXXProcessPacketHeader(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPacketHeader(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPacketRequest(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPacketRequest(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPacketResponse(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPacketResponse(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif